import React, { useState } from 'react';

export default function RobotsSitemapGenerator() {
  const [siteUrl, setSiteUrl] = useState('https://example.com');
  const [sitemapPath, setSitemapPath] = useState('/sitemap.xml');
  const [crawlDelay, setCrawlDelay] = useState('none');
  const [rules, setRules] = useState([
    { id: '1', userAgent: '*', type: 'disallow', path: '/admin/' },
    { id: '2', userAgent: '*', type: 'disallow', path: '/api/' },
    { id: '3', userAgent: '*', type: 'disallow', path: '/private/' },
    { id: '4', userAgent: 'Googlebot', type: 'allow', path: '/' },
  ]);
  const [copiedRobots, setCopiedRobots] = useState(false);

  const addRule = () => {
    setRules([...rules, { id: Date.now().toString(), userAgent: '*', type: 'disallow', path: '/' }]);
  };

  const updateRule = (id, field, value) => {
    setRules(rules.map(r => r.id === id ? { ...r, [field]: value } : r));
  };

  const removeRule = (id) => {
    setRules(rules.filter(r => r.id !== id));
  };

  const generateRobotsTxt = () => {
    const cleanUrl = siteUrl.replace(/\/$/, '');
    let txt = `# Robots.txt generated by Vimz.ai SEO Suite\n# Date: ${new Date().toISOString().split('T')[0]}\n\n`;

    // Group rules by user-agent
    const grouped = {};
    rules.forEach(r => {
      const ua = r.userAgent.trim() || '*';
      if (!grouped[ua]) grouped[ua] = [];
      grouped[ua].push(r);
    });

    Object.entries(grouped).forEach(([ua, ruleList]) => {
      txt += `User-agent: ${ua}\n`;
      if (crawlDelay !== 'none') {
        txt += `Crawl-delay: ${crawlDelay}\n`;
      }
      ruleList.forEach(rule => {
        const directive = rule.type === 'allow' ? 'Allow' : 'Disallow';
        txt += `${directive}: ${rule.path}\n`;
      });
      txt += '\n';
    });

    if (sitemapPath) {
      const fullSitemap = sitemapPath.startsWith('http') ? sitemapPath : `${cleanUrl}${sitemapPath.startsWith('/') ? '' : '/'}${sitemapPath}`;
      txt += `Sitemap: ${fullSitemap}\n`;
    }

    return txt;
  };

  const robotsOutput = generateRobotsTxt();

  const handleCopy = () => {
    navigator.clipboard.writeText(robotsOutput);
    setCopiedRobots(true);
    setTimeout(() => setCopiedRobots(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([robotsOutput], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'robots.txt';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8 space-y-6">
      {/* Header */}
      <div className="bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 text-blue-600 dark:text-blue-400 text-xs font-semibold uppercase tracking-wider mb-2">
              🛡️ Search Crawler Directives
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white">
              Visual Robots.txt & Sitemap Directives Builder
            </h1>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              Create search engine compliant crawler instructions for Googlebot, Bingbot, and AI crawlers with path rules and XML sitemap references.
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-2 px-4 py-2.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl text-sm font-semibold transition-colors"
            >
              {copiedRobots  ? '✓' : '📋'}
              {copiedRobots ? 'Copied!' : 'Copy'}
            </button>
            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-semibold transition-colors shadow-sm"
            >
              📥 Download robots.txt
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Rules Builder */}
        <div className="lg:col-span-7 space-y-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm space-y-5">
            <h2 className="text-base font-semibold text-slate-900 dark:text-white flex items-center gap-2">
              🌐 General Directives
            </h2>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-medium text-slate-600 dark:text-slate-400 mb-1">
                  Website Base URL
                </label>
                <input
                  type="text"
                  value={siteUrl}
                  onChange={(e) => setSiteUrl(e.target.value)}
                  className="w-full px-3.5 py-2 bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-600 dark:text-slate-400 mb-1">
                  Sitemap Path or URL
                </label>
                <input
                  type="text"
                  value={sitemapPath}
                  onChange={(e) => setSitemapPath(e.target.value)}
                  placeholder="/sitemap.xml"
                  className="w-full px-3.5 py-2 bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-600 dark:text-slate-400 mb-1">
                Crawl Delay (Seconds)
              </label>
              <select
                value={crawlDelay}
                onChange={(e) => setCrawlDelay(e.target.value)}
                className="w-full px-3.5 py-2 bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20"
              >
                <option value="none">No Delay (Default)</option>
                <option value="2">2 seconds</option>
                <option value="5">5 seconds</option>
                <option value="10">10 seconds</option>
              </select>
            </div>

            {/* Path Directives */}
            <div className="space-y-3 pt-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                  Crawler Path Rules ({rules.length})
                </span>
                <button
                  onClick={addRule}
                  className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-blue-500/10 hover:bg-blue-500/20 text-blue-600 dark:text-blue-400 text-xs font-medium transition-colors"
                >
                  ➕ Add Rule
                </button>
              </div>

              <div className="space-y-2.5">
                {rules.map((rule) => (
                  <div key={rule.id} className="flex items-center gap-2 bg-slate-50 dark:bg-slate-800/40 p-3 rounded-xl border border-slate-200 dark:border-slate-700">
                    <input
                      type="text"
                      value={rule.userAgent}
                      onChange={(e) => updateRule(rule.id, 'userAgent', e.target.value)}
                      placeholder="User-agent (*)"
                      className="w-28 px-2.5 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-xs"
                    />

                    <select
                      value={rule.type}
                      onChange={(e) => updateRule(rule.id, 'type', e.target.value)}
                      className="w-24 px-2.5 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-medium"
                    >
                      <option value="disallow">Disallow</option>
                      <option value="allow">Allow</option>
                    </select>

                    <input
                      type="text"
                      value={rule.path}
                      onChange={(e) => updateRule(rule.id, 'path', e.target.value)}
                      placeholder="/directory/"
                      className="flex-1 px-2.5 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-mono"
                    />

                    <button
                      onClick={() => removeRule(rule.id)}
                      className="p-1.5 text-slate-400 hover:text-red-500 transition-colors"
                    >
                      🗑️
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Live robots.txt output preview */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm space-y-3">
            <h3 className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider flex items-center gap-2">
              📄 Live robots.txt Output
            </h3>

            <div className="bg-slate-950 rounded-xl p-4 border border-slate-800 font-mono text-xs text-emerald-400 leading-relaxed overflow-x-auto min-h-[300px]">
              <pre>{robotsOutput}</pre>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
